# Generated by Django 5.1.6 on 2025-06-20 16:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Presence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('medecin', 'Médecin'), ('infirmier', 'Infirmier'), ('pharmacien', 'Pharmacien'), ('accueil', 'Accueil')], max_length=20)),
                ('arrivee', models.DateTimeField(default=django.utils.timezone.now)),
                ('depart', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
