# Generated by Django 5.1.6 on 2025-07-14 19:18

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paiement',
            options={'ordering': ['-date_paiement']},
        ),
        migrations.RemoveField(
            model_name='paiement',
            name='utilisateur',
        ),
        migrations.AddField(
            model_name='examen',
            name='patient',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.patient'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paiement',
            name='personnel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.personnel', verbose_name='Utilisateur qui a enregistré le paiement'),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='type_consultation',
            field=models.TextField(choices=[('', '--- Sélectionnez un motif ---'), ('Consultation de routine', 'Consultation de routine'), ('Suivi médical régulier', 'Suivi médical régulier'), ('Demande de certificat médical', 'Demande de certificat médical'), ('Visite annuelle de contrôle', 'Visite annuelle de contrôle'), ('Bilan de santé', 'Bilan de santé'), ('Fièvre persistante', 'Fièvre persistante'), ('Douleur abdominale', 'Douleur abdominale'), ('Maux de tête fréquents', 'Maux de tête fréquents'), ('Douleur thoracique', 'Douleur thoracique'), ('Toux chronique', 'Toux chronique'), ('Fatigue générale', 'Fatigue générale'), ('Essoufflement', 'Essoufflement'), ('Vertiges', 'Vertiges'), ('Palpitations', 'Palpitations'), ('Douleur musculaire', 'Douleur musculaire'), ('Entorse ou foulure', 'Entorse ou foulure'), ('Douleur articulaire', 'Douleur articulaire'), ('Fracture suspectée', 'Fracture suspectée'), ('Lumbago', 'Lumbago'), ('Chute récente', 'Chute récente'), ('Anxiété / stress', 'Anxiété / stress'), ('Troubles du sommeil', 'Troubles du sommeil'), ('Dépression présumée', 'Dépression présumée'), ('Suivi psychologique', 'Suivi psychologique'), ('Burn-out', 'Burn-out'), ('Hypertension artérielle', 'Hypertension artérielle'), ('Douleur cardiaque', 'Douleur cardiaque'), ('Suivi après infarctus', 'Suivi après infarctus'), ('Fièvre chez l’enfant', 'Fièvre chez l’enfant'), ('Vaccination', 'Vaccination'), ('Toux ou rhume', 'Toux ou rhume'), ('Suivi de croissance', 'Suivi de croissance'), ('Douleurs menstruelles', 'Douleurs menstruelles'), ('Retard de règles', 'Retard de règles'), ('Suivi de grossesse', 'Suivi de grossesse'), ('Contraception', 'Contraception'), ('Chutes répétées', 'Chutes répétées'), ('Diminution de mémoire', 'Diminution de mémoire'), ('Douleurs chroniques', 'Douleurs chroniques')], default='Première consultation', max_length=30, verbose_name='Type de consultation'),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='difference_rendue',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Différence rendue'),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='montant_paye',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Montant payé'),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='montant_total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Montant total dû'),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='numero_transaction',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Numéro de transaction'),
        ),
    ]
