# Generated by Django 5.1.6 on 2025-07-14 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_paiement_options_remove_paiement_utilisateur_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examen',
            name='patient',
        ),
    ]
