# Generated by Django 5.1.6 on 2025-07-15 23:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_examen_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='examen',
            name='patient',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.patient'),
            preserve_default=False,
        ),
    ]
